sudo: required

services:
  - docker

script:
  - deployment/build-dev-ui.sh . https://hpi.de/mueller/metaexp-demo-api/
  - deployment/build-production-ui.sh .
  - deployment/run-production-ui.sh
  - docker ps -a

after_script:
  - docker rm -f ui-production-container
